name: Build Owlbot Docker image

on:
  push:
    branches: [ "dockerize" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'owlbot-repo'
    - name: Build the Docker image
      run: docker build . --file owlbot-repo/Dockerfile --tag owlbot:1