name: Build Owlbot Docker image

on:
  push:
    branches: [ "dockerize" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'owlbot-repo'
    - 
      name: Build the Docker image
      run: docker build . --file owlbot-repo/Dockerfile --tag owlbot:1
    -
      name: Authenticate to CNTO DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
