name: Build Owlbot Docker image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: stable

    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'discord-owlbot'
    - 
      name: Build the Docker image
      working-directory: discord-owlbot
      run: docker build . --file Dockerfile --tag cntoarma/owlbot:1.0.0
    -
      name: Authenticate to CNTO DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Publish image to DockerHub
      run: docker image push cntoarma/owlbot:1.0.0
