name: Build Owlbot DEV Docker image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: stable

    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'owlbot-repo'
    - 
      name: Build the Docker image
      run: docker build . --file owlbot-repo/Dockerfile --tag cntoarma/owlbot:latest
    -
      name: Authenticate to CNTO DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Publish image to DockerHub
      run: docker image push cntoarma/owlbot:latest
